server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



#  h2:
#    console:
#      enabled: true
#      path: /h2-console



